public Class ARApexClass
{
public Account createAccount(String name)  //method to create account
{
//Demo for Toyota Team for large implementation
//Comment1 with some more info
//More changes here
//comment2
Account acc112 = new Account();
acc112.Name = name;
Contact con=new Contact();
Opportunity opp = new Opportunity();
Contract ctr = new Contract();
return acc112;
//Demo for VeriMatrix Team
}
}